site_name: wolfMQTT Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Introduction": index.md
    - "2. Building wolfSSH": chapter02.md
    - "3. Getting Started": chapter03.md
    - "4. Library Design": chapter04.md
    - "5. wolfSSH User Authentication Callback": chapter05.md
    - "6. Callback Function Setup API": chapter06.md
    - "7. Building and Using wolfSSH SFTP": chapter07.md
    - "8. Port Forwarding": chapter08.md
    - "9. Notes and Limitations": chapter09.md
    - "10. Licensing ": chapter10.md
    - "11. Support and Consulting": chapter11.md
    - "12. wolfSSH Updates": chapter12.md
    - "13. API Reference": chapter13.md
    - "14. wolfSSL SFTP API Reference": chapter14.md
theme: readthedocs
extra_css: [skin.css]
use_directory_urls: false
