site_name: wolfTPM Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Intro": index.md
    - "2. Building wolfTPM": chapter02.md
    - "3. Getting Started": chapter03.md
    - "4. wolfTPM Library Design": chapter04.md
    - "5. API Reference":
      - "TPM2 API": group__TPM2__Proprietary.md
      - "TPM2 Wrapper API": group__wolfTPM2__Wrappers.md
      - "TPM2 Header File": tpm2_8h.md
      - "TPM2 Wrapper Header File": tpm2__wrap_8h.md
    - "6. Cited Sources": chapter06.md
theme: readthedocs
extra_css: [skin.css]
use_directory_urls: false
