site_name: wolfSSL Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Introduction": index.md
    - "2. Building wolfSSL": chapter02.md
    - "3. Getting Started": chapter03.md
    - "4. Features": chapter04.md
    - "5. Portability": chapter05.md
    - "6. Callbacks": chapter06.md
    - "7. Keys and Certificates": chapter07.md
    - "8. Debugging": chapter08.md
    - "9. Library Design": chapter09.md
    - "10. wolfCrypt Usage Reference": chapter10.md
    - "11. SSL Tutorial": chapter11.md
    - "12. Best Practices for Embedded Devices": chapter12.md
    - "13. OpenSSL Compatibility": chapter13.md
    - "14. Licensing": chapter14.md
    - "15. Support and Consulting": chapter15.md
    - "16. wolfSSL Updates": chapter16.md
    - "17. wolfSSL API Reference": chapter17.md
    - "18. wolfCrypt API Reference": chapter18.md
    - "A. SSL/TLS Overview": appendix01.md
    - "B. RFCs, Specifications, and Reference": appendix02.md
    - "C. Error Codes": appendix03.md
theme: readthedocs
extra_css: [skin.css]
use_directory_urls: false
