site_name: wolfProvider Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: Copyright © 2024 wolfSSL Inc.
nav:
    - "1. Introduction": index.md
    - "2. OpenSSL Version Compatability": chapter02.md
    - "3. Building wolfProvider": chapter03.md
    - "4. FIPS 140-3 Support": chapter04.md
    - "5. Logging": chapter05.md
    - "6. Portability": chapter06.md
    - "7. Loading wolfProvider": chapter07.md
    - "8. wolfProvider Design": chapter08.md
    - "9. Notes on Open Source Integration": chapter09.md
    - "10. Support and OpenSSL Version Adding": chapter10.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: roboto
    code: roboto mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
use_directory_urls: false
