site_name: wolfMQTT Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Introduction": index.md
    - "2. Building wolfMQTT": chapter02.md
    - "3. Getting Started": chapter03.md
    - "4. Library Design": chapter04.md
    - "5. API Reference":
      - mqtt__client_8h.md
      - mqtt__packet_8h.md
      - mqtt__socket_8h.md
      - mqtt__types_8h.md  
theme: readthedocs
extra_css: [skin.css]
use_directory_urls: false
