site_name: wolfSSL Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Introduction": index.md
    - "2. Building wolfSentry": chapter02.md
    - "3. wolfSentry API": chapter03.md
theme: readthedocs
extra_css: [skin.css]
use_directory_urls: false
