site_name: wolfSentry Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: Copyright © 2022 wolfSSL Inc.
nav:
    - "1. Introduction and Build Basics": index.md
    - "2. Building and Initializing wolfSentry for an application on FreeRTOS/lwIP": freertos-lwip-app.md
    - "3. Configuring wolfSentry using a JSON document": json_configuration.md
    - "4. wolfSentry Release History and Change Log": ChangeLog.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: roboto
    code: roboto mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
use_directory_urls: false
